### ISSUE TITLE
Why are there 2 duplication question

### ISSUE THREAD

**Issue by jee-gamer** [knilios/ku-polls#65]
There is a duplication of question "If you have an opportunity to study abroad, which of the following countries do you consider the best choice?"

but doesn't have any choices?
![image](https://github.com/user-attachments/assets/7d314b0b-5d99-455c-984a-525b8520f3d5)
![image](https://github.com/user-attachments/assets/0cd8095a-fffd-485e-b63b-2c922f4154c3)
![image](https://github.com/user-attachments/assets/bc35f04c-2a6d-4438-85fe-ead3ec040479)

**Comment by knilios** [comment]
I have deleted the duplicated question. Thank you for pointing out.
